# Introduction to Tensor

## tensor in PyTorch is just like a NumPy array, but it can run on GPUs and support automatic differentiation (important for deep learning).

## Think of it as a container for numbers, like a list or a table, but with extra features for AI and machine learning.

## Import libraries 

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
print(torch.__version__) # check version of pytorch

2.5.1+cu121


### Scalar

In [4]:
scalar = torch.tensor(5)
scalar

tensor(5)

In [5]:
scalar.ndim # scalar has no dimension.It's just a single number

0

In [6]:
scalar.item() # Get tensor back to python int

5

## Vector

In [7]:
vector = torch.tensor([2,5])
vector

tensor([2, 5])

In [8]:
vector.ndim # vector has one dimension

1

In [9]:
vector.shape

torch.Size([2])

## MATRIX

In [10]:
MATRIX = torch.tensor([[1,2], [4,5]])
MATRIX

tensor([[1, 2],
        [4, 5]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0] # first row

tensor([1, 2])

In [13]:
MATRIX[1] # second row

tensor([4, 5])

In [14]:
MATRIX.shape # four element in the matrix

torch.Size([2, 2])

## TENSOR

In [15]:
TENSOR = torch.tensor([[[1,2],
                       [3,4],
                       [5,6]]])
TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape # 1 for first bracket, 3 for three rows and 2 for two colums

torch.Size([1, 3, 2])

## Random numbers

### Why random numbers ?
### Random tensors are important because the way many neural networks learn is that thay start with tensors full of
### random numbers and then adjust those random numbers to better represent the data.
### Start with random numbers -> look at the data -> update random numbers -> look at the data ->
### update random numbers.

In [18]:
# Create a random tensor of size (3, 4) . 3 rows and 4 columns
import torch
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9239, 0.2957, 0.1318, 0.2924],
        [0.1644, 0.2613, 0.7440, 0.8233],
        [0.1746, 0.9292, 0.4391, 0.1548]])

In [19]:
# random image tensor (color channel(Red, Green, Blue), height , width)
random_image_tensor = torch.rand(size=(3, 224, 224))
random_image_tensor 

tensor([[[0.8708, 0.8453, 0.3897,  ..., 0.4268, 0.9183, 0.2152],
         [0.1549, 0.6579, 0.2848,  ..., 0.5979, 0.5042, 0.1853],
         [0.0116, 0.2801, 0.1824,  ..., 0.5606, 0.2628, 0.4368],
         ...,
         [0.9879, 0.9029, 0.8700,  ..., 0.2583, 0.0186, 0.9399],
         [0.7272, 0.2622, 0.8008,  ..., 0.5053, 0.7561, 0.1139],
         [0.0073, 0.4196, 0.1082,  ..., 0.2163, 0.8123, 0.4313]],

        [[0.8264, 0.5197, 0.7801,  ..., 0.7362, 0.8438, 0.2852],
         [0.2736, 0.6418, 0.9942,  ..., 0.4339, 0.3486, 0.7780],
         [0.2871, 0.3605, 0.6648,  ..., 0.6540, 0.2927, 0.3438],
         ...,
         [0.4519, 0.5058, 0.6132,  ..., 0.3280, 0.8640, 0.1019],
         [0.5863, 0.5019, 0.4842,  ..., 0.5974, 0.8478, 0.8853],
         [0.9878, 0.5418, 0.9680,  ..., 0.7984, 0.5328, 0.4892]],

        [[0.7620, 0.9116, 0.5027,  ..., 0.2601, 0.3030, 0.0610],
         [0.3205, 0.8166, 0.1027,  ..., 0.7952, 0.9389, 0.7881],
         [0.6636, 0.4557, 0.3829,  ..., 0.2968, 0.7232, 0.

In [20]:
random_image_tensor.ndim # dimension

3

In [21]:
random_image_tensor.shape

torch.Size([3, 224, 224])

In [22]:
random_image_tensor.numel() # use to find no. of element 

150528

# Zeros and Ones

In [23]:
# Create a tensor with all zeros
x = torch.zeros(size=(3,2)) # 3 rows and 2 columns
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [24]:
# Create a tensor with all ones
x = torch.ones(size=(3,3)) # 3 rows and 3 colums
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
# When we multiply random numbers with zeros
x = torch.rand(3,3)
y = torch.zeros(size=(3,3))
z = x * y
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## Creating a range of tensors and tensor_like

In [26]:
# arange(start, end, step)
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [27]:
# Tensor that filled with zeroes using zeros_like(input=) or ones_like(input=)
one_to_ten = torch.arange(1,11,2)
all_zeros = torch.zeros_like(input=one_to_ten)
all_zeros

tensor([0, 0, 0, 0, 0])

## Tensor Datatypes:
### Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning.
### 1. Tensors not right datatype
### 2. Tensors not right shape
### 3. Tensors not on the right device


In [28]:
tensor_int64_by_default = torch.tensor([1,2,3,4], dtype=None, device=None, requires_grad=False)
tensor_int64_by_default.dtype

torch.int64

In [29]:
# If you are working on GPU change device into "cuda" and if not then 'cpu'
tensor_float32_by_default = torch.tensor([1.0, 2.0, 3.0], dtype=None, device=None, requires_grad=False)
tensor_float32_by_default.dtype

torch.float32

#### dtype = None ,-> What datatype is the tensor (e.g. float32 or int64).
####  device = None, -> What device is your tensor on.
#### requires_grad = False, -> Whether or not track gradients with this tensors operations.

In [30]:
# I want to change datatype into int64 
tensor_float32 = torch.tensor([1.9, 1.3, 1.1], dtype=torch.int64)
tensor_float32.dtype
tensor_int64 = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor_float32 * tensor_int64

tensor([1., 2., 3.])

#### change datatype

In [31]:
# create int64 change into float16
int_64_tensor = torch.tensor([1,2,3,4], dtype=torch.int64)
change_into_float16 = int_64_tensor.type(torch.float16)
change_into_float16

tensor([1., 2., 3., 4.], dtype=torch.float16)

## Get Information from tensors. (tensor attribute).
### 1. Tensors not right datatype. To find datatype use: tensor.dtype
### 2. Tensors not right shape.    To find shape use: tensor.shape
### 3. Tensors not on the right device. To find which device on use : tensor.device


In [32]:
# create a random tensor
random_tensor = torch.rand(3,2)
random_tensor

tensor([[0.8454, 0.3553],
        [0.7889, 0.4361],
        [0.8075, 0.3865]])

In [33]:
# Now getting information 
print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Shape of tensor: {random_tensor.shape}")
print(f"Device tensor is on: {random_tensor.device} ")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 2])
Device tensor is on: cpu 


## Manipulating tensor : Tensor Operation.
* Addition.
* Subtraction.
* Multiplication
* Division.


In [34]:
# Create a tensor
# Add 10 to it
x = torch.tensor([1,2,3,4,5]) 
x + 1 

tensor([2, 3, 4, 5, 6])

In [35]:
# Subtraction
x - 1

tensor([0, 1, 2, 3, 4])

In [36]:
# Multiplication
x * 10

tensor([10, 20, 30, 40, 50])

In [37]:
# Division
x / 2

tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [38]:
# Also use in-built function
torch.mul(x, 10) # Multiplication

tensor([10, 20, 30, 40, 50])

In [39]:
# Addition
torch.add(x, 1)

tensor([2, 3, 4, 5, 6])

In [40]:
# Subtraction
torch.sub(x,1)

tensor([0, 1, 2, 3, 4])

In [41]:
# Division
torch.div(x, 2)

tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

## Matrix Multiplication
### Matrix multiplication (element-wise)
### Matrix multiplication.(dot product). (most commonly use in neural network and deep learning)
#### There are two main rules that performing matrix multiplication (dot product) needs satisfy.
1. The inner dimensions must match:
* (3,2) & (3,2) won't work.
* (2,3) & (3,2) will work. because inner dimensions match is (3,3)
2. The Outer dimensions
* (2,3) & (3,2) -> (2,2) result

In [42]:
# element-wise
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[2,2,2],[1,2,1]])
z = x * y
z

tensor([[ 2,  4,  6],
        [ 4, 10,  6]])

In [43]:
# Matrix multiplication(dot product)
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8],[9,10],[11,12]])
z = torch.mm(x,y)
z

tensor([[ 58,  64],
        [139, 154]])

#### One of the most common errors in deep learning : shape errors.
* We can use Transpose to fix that issues.By matching the inner dimension we can fix that error.

In [44]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[1,1,1],[2,2,2]]) # RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)
# To fix this error using transpose.
y_transpose = y.T
z = torch.mm(x,y_transpose)
z

tensor([[ 6, 12],
        [15, 30]])

## Finding the min, max, mean, sum etc (tensor aggregation).

In [45]:
# Create a tensor
x = torch.arange(1, 100, 14)
x

tensor([ 1, 15, 29, 43, 57, 71, 85, 99])

In [46]:
# Find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [47]:
# Find max
torch.max(x), x.max()

(tensor(99), tensor(99))

In [48]:
# Find mean. Note: Whenever when we find mean use float datatype otherwise it will give error.
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [49]:
# Find sum
torch.sum(x), x.sum()

(tensor(400), tensor(400))

## Finding the positional min and max

In [50]:
x = torch.arange(1, 10, 1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# Find argmin() which return the minimun value index and we use that index to find value.
torch.argmin(x)

tensor(0)

In [52]:
x[0] # on first index the mini value present

tensor(1)

In [53]:
# Find argmax()
torch.argmax(x)

tensor(8)

In [54]:
x[8] # on index 8 the max value present

tensor(9)

## Reshaping, stacking, squeezing and unsequeezing tensors.
* Reshaping - reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack).
* Squeeze - remove all 1 dimension from a tensor.
* Unsqueeze - add 1 dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [55]:
# Create a tensor
x = torch.arange(1, 13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
x.shape

torch.Size([12])

#### Reshaping

In [57]:
# Change from 1 dimension into 2 dimension by using reshape.
x.reshape(3,4) # 3 rows and 4 columns

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [58]:
# Change from 2D to 1D using reshape(-1)
x.reshape(-1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### View

In [59]:

y = x.view(-1,2) # 2D array which every row contain 2 elements.
y

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

In [60]:
x[0] = 22 # changing in original array also change new view array.
y

tensor([[22,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

#### Stack()

In [61]:
# Create two tensor and then concatenate it with help of stack.
x = torch.arange(1,11)
y = torch.arange(11, 21)
z = torch.stack([x,y], dim=0) # when use dim=0 it become horizontal and when use dim=1 it become vertical.
z

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

#### Squeeze() method use to remove a single dimension from a target tensor.

In [62]:
# Create a tensor
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# Reshape it
x_reshape = x.reshape(1,1,9) # Three dimension
x_reshape

tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [64]:
print(f"Previous tensor before squeeze: {x_reshape}")
print(f"Previous tensor shape:{x_reshape.shape}")

# After squeeze
y = x_reshape.squeeze()   # it will remove all one's and convert it into one dimension.
print(f"\nAfter squeeze: {y}")
print(f"After squeeze shape: {y.shape}")

Previous tensor before squeeze: tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])
Previous tensor shape:torch.Size([1, 1, 9])

After squeeze: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
After squeeze shape: torch.Size([9])


#### unsqueeze(dim=0) is used to add 1 to the tensor.

In [65]:
# Create a tensor 
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x.shape

torch.Size([9])

In [67]:
print(f"Previous tensor: {x}")
print(f"Previous tensor shape: {x.shape}")

# After unsqueeze()
y = x.unsqueeze(dim=0)
print(f"\nAfter unsqueeze: {y}")
print(f"After unsqueeze shape: {y.shape}")

Previous tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous tensor shape: torch.Size([9])

After unsqueeze: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
After unsqueeze shape: torch.Size([1, 9])


#### permute() is used to change axis of the tensor.

In [68]:
# Create a random image tensor
x_image = torch.rand(24, 24, 3) # height , width, and colour_channels (0,1,2)
x_image.shape

torch.Size([24, 24, 3])

In [69]:
change_axis = x_image.permute(2,0,1) # colour_channels, height and width
change_axis.shape

torch.Size([3, 24, 24])

In [70]:
# Permute work like view. Make changes in the original tensor will change the new tensor.
x_image[0,0,0] = 12123
# check both of the tensor
x_image[0,0,0], change_axis[0,0,0]

(tensor(12123.), tensor(12123.))

## Indexing (selecting data from tensors)
#### Indexing with PyTorch is similar to indexing with NumPy.

In [71]:
# Create a tensor
y = torch.arange(1,10).reshape(1,3,3) # 3D 
y, y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
# Let's index on our new tensor
y[0] 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
# Let's index on the middle bracket (dim=1)
y[0][0] # return first row 

tensor([1, 2, 3])

In [74]:
# Let's index on the most inner bracket (last dimension)
y[0][0][0] # return first row of first element

tensor(1)

In [75]:
# Find the whole 3rd column
y[0, :, 2] # second is rows and third is for colums

tensor([3, 6, 9])

In [76]:
# access only 5, 8 element of the column
y[0,1:,1:2]

tensor([[5],
        [8]])

## PyTorch and NumPy:
#### Convert Numpy into PyTorch using torch.from_numpy()
#### Convert PyTorch into NumPy using torch.numpy()

In [77]:
# Convert NumPy into PyTorch
import torch
numpy_array = np.arange(1.0,11.0)
numpy_to_torch = torch.from_numpy(numpy_array)
numpy_array, numpy_to_torch

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [78]:
numpy_array.dtype, numpy_to_torch.dtype

(dtype('float64'), torch.float64)

In [79]:
# PyTorch into NumPy
pytorch_to_numpy = numpy_to_torch.numpy()
pytorch_to_numpy

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## PyTorch reproducibility (taking the random out of random):
#### In short how a neural network learns:
#### start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again.
#### To reduce the randomness in neural networks and PyTorch comes the concept of a ** random seed **.
#### Essentially what the random seed does is "flavour" the randomness.

In [80]:
# Let's make some random tensors
random_tensor_A = torch.rand(3,3)
random_tensor_B = torch.rand(3,3)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7669, 0.3858, 0.4440],
        [0.7743, 0.1670, 0.9484],
        [0.1678, 0.3882, 0.7597]])
tensor([[0.8081, 0.6116, 0.5267],
        [0.0383, 0.6855, 0.1671],
        [0.7534, 0.0888, 0.6135]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [81]:
# reproducibility 
RANDOM_SEED = 44

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,3)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.7196, 0.7307, 0.8278],
        [0.1343, 0.6280, 0.7297],
        [0.2882, 0.2112, 0.9836]])
tensor([[0.7196, 0.7307, 0.8278],
        [0.1343, 0.6280, 0.7297],
        [0.2882, 0.2112, 0.9836]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Check for GPU access to PyTorch:

In [82]:
import torch
torch.cuda.is_available()

True

In [83]:
# Setup device agnostic code:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [84]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU
### The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [85]:
# Create a tensor by default on the CPU
tensor = torch.tensor([1,2,3,4])

print(tensor, tensor.device)

tensor([1, 2, 3, 4]) cpu


In [86]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4], device='cuda:0')

## Moving tensor back to the CPU


In [88]:
# if tensor is on GPU, can't transform is to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [90]:
# To fix this issue first convert back into cpu 
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3, 4])

In [91]:
tensor_on_gpu

tensor([1, 2, 3, 4], device='cuda:0')